"use client";

import { create } from "zustand";

/**
 * Lights Out — 5×5 grid. Clicking a cell toggles itself plus its 4 orthogonal
 * neighbours. Goal: turn every cell off. Starting boards are generated by
 * applying N random toggles to the all-off state, guaranteeing solvability.
 *
 * State persists in localStorage so the user can minimize mid-puzzle and
 * resume from the pill.
 */

export const SIZE = 5;
const CELLS = SIZE * SIZE;
const SHUFFLE_TOGGLES = 8;

type Status = "playing" | "won";

type State = {
  grid: boolean[];
  moves: number;
  bestMoves: number;
  startedAt: number | null;
  endedAt: number | null;
  bestMs: number;
  status: Status;
  /** Per-cell key that bumps each time the cell toggles; used by the view to
   *  retrigger the cell's pulse animation without remounting. */
  toggleNonce: number[];
};

type Actions = {
  toggle: (idx: number) => void;
  restart: () => void;
  hydrate: () => void;
};

const STORAGE_KEY = "rrl:lights-out";

const allOff = (): boolean[] => Array.from({ length: CELLS }, () => false);

function applyToggle(grid: boolean[], idx: number, nonces: number[]): { grid: boolean[]; nonces: number[] } {
  const next = grid.slice();
  const nextNonces = nonces.slice();
  const r = Math.floor(idx / SIZE);
  const c = idx % SIZE;
  const targets = [[r, c], [r - 1, c], [r + 1, c], [r, c - 1], [r, c + 1]];
  for (const [tr, tc] of targets) {
    if (tr < 0 || tr >= SIZE || tc < 0 || tc >= SIZE) continue;
    const i = tr * SIZE + tc;
    next[i] = !next[i];
    nextNonces[i] = (nextNonces[i] ?? 0) + 1;
  }
  return { grid: next, nonces: nextNonces };
}

function makePuzzle(): { grid: boolean[]; nonces: number[] } {
  let grid = allOff();
  let nonces = Array.from({ length: CELLS }, () => 0);
  let lastIdx = -1;
  for (let n = 0; n < SHUFFLE_TOGGLES; n++) {
    let idx: number;
    do {
      idx = Math.floor(Math.random() * CELLS);
    } while (idx === lastIdx);
    lastIdx = idx;
    const next = applyToggle(grid, idx, nonces);
    grid = next.grid;
    nonces = next.nonces;
  }
  // Edge case: if shuffling happened to land on all-off, redo.
  if (grid.every((c) => !c)) return makePuzzle();
  return { grid, nonces: Array.from({ length: CELLS }, () => 0) };
}

const initial = (): State => {
  const { grid, nonces } = makePuzzle();
  return {
    grid,
    moves: 0,
    bestMoves: 0,
    startedAt: null,
    endedAt: null,
    bestMs: 0,
    status: "playing",
    toggleNonce: nonces,
  };
};

function persist(s: State) {
  if (typeof window === "undefined") return;
  try {
    localStorage.setItem(
      STORAGE_KEY,
      JSON.stringify({
        grid: s.grid,
        moves: s.moves,
        bestMoves: s.bestMoves,
        startedAt: s.startedAt,
        endedAt: s.endedAt,
        bestMs: s.bestMs,
        status: s.status,
      })
    );
  } catch {
    /* storage unavailable */
  }
}

function rehydrate(): Partial<State> {
  if (typeof window === "undefined") return {};
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (!raw) return {};
    const parsed = JSON.parse(raw) as Partial<State>;
    if (!Array.isArray(parsed.grid) || parsed.grid.length !== CELLS) return {};
    return {
      grid: parsed.grid as boolean[],
      moves: typeof parsed.moves === "number" ? parsed.moves : 0,
      bestMoves: typeof parsed.bestMoves === "number" ? parsed.bestMoves : 0,
      startedAt: typeof parsed.startedAt === "number" ? parsed.startedAt : null,
      endedAt: typeof parsed.endedAt === "number" ? parsed.endedAt : null,
      bestMs: typeof parsed.bestMs === "number" ? parsed.bestMs : 0,
      status: parsed.status === "won" ? "won" : "playing",
    };
  } catch {
    return {};
  }
}

export const useLightsOut = create<State & Actions>((set, get) => ({
  ...initial(),

  hydrate: () => {
    const restored = rehydrate();
    const next = { ...initial(), ...restored };
    // Reset nonces — the view will only retrigger animations on new toggles.
    next.toggleNonce = Array.from({ length: CELLS }, () => 0);
    set(next);
  },

  toggle: (idx) => {
    const s = get();
    if (s.status === "won") return;
    const startedAt = s.startedAt ?? Date.now();
    const { grid, nonces } = applyToggle(s.grid, idx, s.toggleNonce);
    const moves = s.moves + 1;
    const won = grid.every((c) => !c);
    const endedAt = won ? Date.now() : s.endedAt;
    const elapsed = won && startedAt ? endedAt! - startedAt : 0;
    const bestMs = won && (s.bestMs === 0 || elapsed < s.bestMs) ? elapsed : s.bestMs;
    const bestMoves = won && (s.bestMoves === 0 || moves < s.bestMoves) ? moves : s.bestMoves;
    const next: State = {
      ...s,
      grid,
      toggleNonce: nonces,
      moves,
      bestMoves,
      startedAt,
      endedAt: won ? endedAt : null,
      bestMs,
      status: won ? "won" : "playing",
    };
    set(next);
    persist(next);
  },

  restart: () => {
    const s = get();
    const { grid, nonces } = makePuzzle();
    const next: State = {
      ...initial(),
      grid,
      toggleNonce: nonces,
      bestMoves: s.bestMoves,
      bestMs: s.bestMs,
    };
    set(next);
    persist(next);
  },
}));
