"use client";

import { create } from "zustand";

/**
 * 15-puzzle — 4×4 grid, 15 numbered tiles + 1 empty slot. Slide tiles into
 * 1-15 order with empty in the bottom-right. Shuffle is generated by walking
 * the empty cell randomly through N valid moves from the solved state, so
 * every starting board is guaranteed solvable.
 */

export const COLS = 4;
export const ROWS = 4;
export const SIZE = COLS * ROWS;

type Status = "playing" | "won";

type State = {
  /** Length-16 array of tile values in row-major order; 0 = empty. */
  tiles: number[];
  /** Index 0..15 where the empty slot currently sits. */
  emptyIdx: number;
  moves: number;
  bestMoves: number;
  startedAt: number | null;
  endedAt: number | null;
  bestMs: number;
  status: Status;
};

type Actions = {
  /** Try to slide the tile at `idx` into the empty slot. No-op if not adjacent. */
  slide: (idx: number) => void;
  /** Slide the tile that lies in the given direction of the empty slot. */
  slideDir: (dir: "up" | "down" | "left" | "right") => void;
  restart: () => void;
  hydrate: () => void;
};

const STORAGE_KEY = "rrl:slide-puzzle";

function solved(): number[] {
  const out: number[] = [];
  for (let i = 1; i < SIZE; i++) out.push(i);
  out.push(0);
  return out;
}

function isSolved(tiles: number[]): boolean {
  for (let i = 0; i < SIZE - 1; i++) if (tiles[i] !== i + 1) return false;
  return tiles[SIZE - 1] === 0;
}

function rowCol(idx: number): [number, number] {
  return [Math.floor(idx / COLS), idx % COLS];
}

function areAdjacent(a: number, b: number): boolean {
  const [ar, ac] = rowCol(a);
  const [br, bc] = rowCol(b);
  return (ar === br && Math.abs(ac - bc) === 1) || (ac === bc && Math.abs(ar - br) === 1);
}

function shuffleFromSolved(steps = 120): { tiles: number[]; emptyIdx: number } {
  const tiles = solved();
  let emptyIdx = SIZE - 1;
  let lastEmpty = -1;
  for (let s = 0; s < steps; s++) {
    const [er, ec] = rowCol(emptyIdx);
    const candidates: number[] = [];
    if (er > 0) candidates.push(emptyIdx - COLS);
    if (er < ROWS - 1) candidates.push(emptyIdx + COLS);
    if (ec > 0) candidates.push(emptyIdx - 1);
    if (ec < COLS - 1) candidates.push(emptyIdx + 1);
    // Avoid backtracking immediately for more visual variety.
    const choices = candidates.filter((c) => c !== lastEmpty);
    const pick = (choices.length > 0 ? choices : candidates)[
      Math.floor(Math.random() * (choices.length > 0 ? choices.length : candidates.length))
    ];
    tiles[emptyIdx] = tiles[pick];
    tiles[pick] = 0;
    lastEmpty = emptyIdx;
    emptyIdx = pick;
  }
  return { tiles, emptyIdx };
}

const initial = (): State => {
  const { tiles, emptyIdx } = shuffleFromSolved();
  return {
    tiles,
    emptyIdx,
    moves: 0,
    bestMoves: 0,
    startedAt: null,
    endedAt: null,
    bestMs: 0,
    status: "playing",
  };
};

function persist(s: State) {
  if (typeof window === "undefined") return;
  try {
    localStorage.setItem(
      STORAGE_KEY,
      JSON.stringify({
        tiles: s.tiles,
        emptyIdx: s.emptyIdx,
        moves: s.moves,
        bestMoves: s.bestMoves,
        startedAt: s.startedAt,
        endedAt: s.endedAt,
        bestMs: s.bestMs,
        status: s.status,
      })
    );
  } catch {
    /* storage unavailable */
  }
}

function rehydrate(): Partial<State> {
  if (typeof window === "undefined") return {};
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (!raw) return {};
    const parsed = JSON.parse(raw) as Partial<State>;
    if (!Array.isArray(parsed.tiles) || parsed.tiles.length !== SIZE) return {};
    return {
      tiles: parsed.tiles as number[],
      emptyIdx: typeof parsed.emptyIdx === "number" ? parsed.emptyIdx : (parsed.tiles as number[]).indexOf(0),
      moves: typeof parsed.moves === "number" ? parsed.moves : 0,
      bestMoves: typeof parsed.bestMoves === "number" ? parsed.bestMoves : 0,
      startedAt: typeof parsed.startedAt === "number" ? parsed.startedAt : null,
      endedAt: typeof parsed.endedAt === "number" ? parsed.endedAt : null,
      bestMs: typeof parsed.bestMs === "number" ? parsed.bestMs : 0,
      status: parsed.status === "won" ? "won" : "playing",
    };
  } catch {
    return {};
  }
}

export const useSlidePuzzle = create<State & Actions>((set, get) => ({
  ...initial(),

  hydrate: () => {
    const restored = rehydrate();
    set({ ...initial(), ...restored });
  },

  slide: (idx) => {
    const s = get();
    if (s.status === "won") return;
    if (!areAdjacent(idx, s.emptyIdx)) return;
    const tiles = [...s.tiles];
    tiles[s.emptyIdx] = tiles[idx];
    tiles[idx] = 0;
    const moves = s.moves + 1;
    const startedAt = s.startedAt ?? Date.now();
    const won = isSolved(tiles);
    const endedAt = won ? Date.now() : s.endedAt;
    const elapsed = won && startedAt ? endedAt! - startedAt : 0;
    const bestMs = won && (s.bestMs === 0 || elapsed < s.bestMs) ? elapsed : s.bestMs;
    const bestMoves = won && (s.bestMoves === 0 || moves < s.bestMoves) ? moves : s.bestMoves;
    const next: State = {
      ...s,
      tiles,
      emptyIdx: idx,
      moves,
      bestMoves,
      startedAt,
      endedAt: won ? endedAt : null,
      bestMs,
      status: won ? "won" : "playing",
    };
    set(next);
    persist(next);
  },

  slideDir: (dir) => {
    const s = get();
    const [er, ec] = rowCol(s.emptyIdx);
    // Arrow direction = which way the tile slides. Tile to slide sits
    // opposite of the direction from the empty slot.
    let tileIdx = -1;
    if (dir === "up" && er < ROWS - 1) tileIdx = s.emptyIdx + COLS;
    if (dir === "down" && er > 0) tileIdx = s.emptyIdx - COLS;
    if (dir === "left" && ec < COLS - 1) tileIdx = s.emptyIdx + 1;
    if (dir === "right" && ec > 0) tileIdx = s.emptyIdx - 1;
    if (tileIdx >= 0) get().slide(tileIdx);
  },

  restart: () => {
    const s = get();
    const next: State = {
      ...initial(),
      bestMoves: s.bestMoves,
      bestMs: s.bestMs,
    };
    set(next);
    persist(next);
  },
}));
